/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as ReinitialiserRouteImport } from './routes/reinitialiser'
import { Route as CheckoutPackageIdRouteImport } from './routes/checkout.$packageId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CommandeIdRouteImport } from './routes/commande.$id'
import { Route as JeuSlugRouteImport } from './routes/jeu.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserRoute = ReinitialiserRouteImport.update({
  id: '/reinitialiser',
  path: '/reinitialiser',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPackageIdRoute = CheckoutPackageIdRouteImport.update({
  id: '/checkout/$packageId',
  path: '/checkout/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeIdRoute = CommandeIdRouteImport.update({
  id: '/commande/$id',
  path: '/commande/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuSlugRoute = JeuSlugRouteImport.update({
  id: '/jeu/$slug',
  path: '/jeu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/compte': typeof CompteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialiser': typeof ReinitialiserRoute
  '/checkout/$packageId': typeof CheckoutPackageIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/commande/$id': typeof CommandeIdRoute
  '/jeu/$slug': typeof JeuSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/compte': typeof CompteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialiser': typeof ReinitialiserRoute
  '/checkout/$packageId': typeof CheckoutPackageIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/commande/$id': typeof CommandeIdRoute
  '/jeu/$slug': typeof JeuSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/compte': typeof CompteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reinitialiser': typeof ReinitialiserRoute
  '/checkout/$packageId': typeof CheckoutPackageIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/commande/$id': typeof CommandeIdRoute
  '/jeu/$slug': typeof JeuSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boutique'
    | '/compte'
    | '/connexion'
    | '/contact'
    | '/faq'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/reinitialiser'
    | '/checkout/$packageId'
    | '/checkout/return'
    | '/commande/$id'
    | '/jeu/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boutique'
    | '/compte'
    | '/connexion'
    | '/contact'
    | '/faq'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/reinitialiser'
    | '/checkout/$packageId'
    | '/checkout/return'
    | '/commande/$id'
    | '/jeu/$slug'
  id:
    | '__root__'
    | '/'
    | '/boutique'
    | '/compte'
    | '/connexion'
    | '/contact'
    | '/faq'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/reinitialiser'
    | '/checkout/$packageId'
    | '/checkout/return'
    | '/commande/$id'
    | '/jeu/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CompteRoute: typeof CompteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InscriptionRoute: typeof InscriptionRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  ReinitialiserRoute: typeof ReinitialiserRoute
  CheckoutPackageIdRoute: typeof CheckoutPackageIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CommandeIdRoute: typeof CommandeIdRoute
  JeuSlugRoute: typeof JeuSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser': {
      id: '/reinitialiser'
      path: '/reinitialiser'
      fullPath: '/reinitialiser'
      preLoaderRoute: typeof ReinitialiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$packageId': {
      id: '/checkout/$packageId'
      path: '/checkout/$packageId'
      fullPath: '/checkout/$packageId'
      preLoaderRoute: typeof CheckoutPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/$id': {
      id: '/commande/$id'
      path: '/commande/$id'
      fullPath: '/commande/$id'
      preLoaderRoute: typeof CommandeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeu/$slug': {
      id: '/jeu/$slug'
      path: '/jeu/$slug'
      fullPath: '/jeu/$slug'
      preLoaderRoute: typeof JeuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoutiqueRoute: BoutiqueRoute,
  CompteRoute: CompteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InscriptionRoute: InscriptionRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  ReinitialiserRoute: ReinitialiserRoute,
  CheckoutPackageIdRoute: CheckoutPackageIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CommandeIdRoute: CommandeIdRoute,
  JeuSlugRoute: JeuSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
